language: node_js
node_js:
- '8'

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-npm
cache:
  directories:
  - node_modules

# generated via "travis setup heroku" | after "travis login --github-token TOKEN" and "heroku login" @ https://github.com/acdcjunior/docker-heroku-travis
deploy:
  provider: heroku
  api_key:
    secure: M+PAICcrnbbHc7h8KLX+1gUVFrHKu2yFL/+ullLSw/KLA9fa438R1PGptVjmK0lX4B6ar/YvhJu4QYHi3MiMjgzBbP80ideN6nNubvxnAh9xrinzvzdz4DDzuDfmhjSnUiXGj5qI3E2F1QvaZNJbRYbyGTpQunGhlstgQStep9HCwPEQHdouGjCGumT7OS91O6ygSNXEJf19VAxzRNwkW9gTSbBvWSyd6iiQ7lC8WjGGpohxJr0hfymcEJ2cHB+fMIfepGpgrcdQYztbGdXrwnALZ5vGawUbZAv5HEQ18FI3TQs2JIEZkE3i1f8A++qt1tmhkt3WwDHf4rMAWrpLT3BE/ukUSDTXU4bkC81H2e6w2gqIKqdBg3VaEKZ6RQLGYMM3tO/rJWiFybe7X33QEQXOxwxfvruszsXxIfkBSbfewZJDjSLEn781Qo0yaqEgJYBtnY9XDrxhw5gCy0mVjJACPpZLLUJYuleo0NJtwnV0mKZnffHMvyyNOT4ae5qjE+gM1up9EDEBk2f7/0EOmCWwXXm5xbly6QwWZRmwBGng6l9/FMa3tJmyq0ddoTY9g1cheLYEFZ7eQuXI2vMZtc8ENbBkLqwRTMbV+oJdTH9M38qsCU0j+t0y80qYDh8Krtge3PEAkGTnsvZhcIItJS2Sb3ddtnev/8qdut9pK04=
  app: code-revue
  on:
    repo: acdcjunior/code-revue-backend
